### ISSUE TITLE
Bug : migration **quantique**

### ISSUE THREAD

**Issue by LightInn** [For-Hives/api-my-makeup#15]
![image](https://user-images.githubusercontent.com/28759336/230108956-bac75a4f-ef31-4624-8868-3557e4e33b5e.png)

create migrations

**Comment by CinquinAndy** [comment]
t'as pété l'api 😣😱😱

**Comment by CinquinAndy** [comment]
c'était pas marqué quantique, 👎

**Comment by CinquinAndy** [comment]
ah bah là c'est mieux !

**Comment by CinquinAndy** [comment]
mais il est toujours quantique :(

**Comment by LightInn** [comment]
Ok, visiblement c'est un bug lier a la derniere version de strapi, mais j'ai une piste : 
https://forum.strapi.io/t/hosting-on-railway-401-error-after-inactivity/21748/12

Je vais tenter d'augmenter le pool de connexions
