### ISSUE TITLE
API Conception - Question

### ISSUE THREAD

**Issue by CinquinAndy** [For-Hives/api-my-makeup#22]
Lorsqu'on crée un utilisateur : 
![image](https://user-images.githubusercontent.com/55706543/232289812-e2741449-497b-4eda-9b8c-a084a5862220.png)

de base, aucun lien vers aucun "makeup_artiste" n'est fait 
![image](https://user-images.githubusercontent.com/55706543/232289821-fb21f7ea-2bed-48a7-8c70-ac9434e7f440.png)

Normal, aucun makeup artist est créer 
![image](https://user-images.githubusercontent.com/55706543/232289830-fadfcfc2-80ee-4928-a95e-c87b1cf8f2df.png)

Comment on fait pour créer une nouvelle "makeup_artist" à la création d'un nouvel utilisateur, en faisant le lien directement vers un nouveau makeup artist, sans donner le droit d'en créer pour autant via l'api ?  
On aurait pas dû étendre la collection "user" plutôt ?

**Comment by LightInn** [comment]
Le truc c'est que la classe user est partager avec les comptes super admin ou encore enventuellement les clients si un jour on les rajoute

On ne veux donc pas systematiquement creer un nouveau makeup_artist pour chaque nouvelle utilisateur, c'est pour ca que pour moi c'est en deux table et en deux commande

**Comment by CinquinAndy** [comment]
Du coup, il faut trouver un moyen de créer une nouvelle entrée " makeup artiste " pour l'utilisateur connecté , on peut limiter un champ pour faire en sorte qu'un utilisateur puisse avoir le droit de créer que sa propre entrée qui lui correspond ? 

car là, ça nous oblige à laisser le droit de création d'une maquilleuse, il faudrait trouver un moyen de le bloquer à une seule création & qu'on puisse créer que la sienne, mais là je sais pas comment faire avec strapi ?

**Comment by LightInn** [comment]
C'est faisable, il faudra juste creer une route custom pour ca mais ca vas se faire sans soucis

**Comment by CinquinAndy** [comment]
okiii, on fait ça alors
