### ISSUE TITLE
Bug accès des images S3 

### ISSUE THREAD

**Issue by CinquinAndy** [For-Hives/api-my-makeup#25]
![image](https://user-images.githubusercontent.com/55706543/232292226-796c3e8d-b301-4821-86b6-e1c87d2738fa.png)

![image](https://user-images.githubusercontent.com/55706543/232292249-2d660805-ca65-4b4e-841f-87688407dda3.png)

![image](https://user-images.githubusercontent.com/55706543/232292266-64bd3441-cd22-4807-95fe-c3d1a8c6bcfb.png)

je crois il y a un problème avec le bucket

**Comment by LightInn** [comment]
bizarre ca :
![image](https://user-images.githubusercontent.com/28759336/232309087-c4cf40ba-53f6-4fea-8ab6-b2037e00e852.png)

On dirais que quelqu'un a toucher au droit de lecture ou un truc du genre

**Comment by LightInn** [comment]
ca devrais etre mieux comme ca  
![image](https://user-images.githubusercontent.com/28759336/232309208-555a13db-9755-4563-81e1-18e658fc2059.png)

**Comment by LightInn** [comment]
> ca devrais etre mieux comme ca ![image](https://user-images.githubusercontent.com/28759336/232309208-555a13db-9755-4563-81e1-18e658fc2059.png)

yep 
![image](https://user-images.githubusercontent.com/28759336/232309342-3ef4464c-8cf3-4e45-b720-83c16d7fce66.png)

**Comment by CinquinAndy** [comment]
perfect ♥
