### ISSUE TITLE
Ajout d'un champ pour la date de disponibilité en plus dans makeup artiste

### ISSUE THREAD

**Issue by CinquinAndy** [For-Hives/api-my-makeup#47]
![image](https://user-images.githubusercontent.com/55706543/235005590-65f2cd20-8baf-45fa-ad9e-22a70d2d02f6.png)
pour cette partie

**Comment by LightInn** [comment]
> ![image](https://user-images.githubusercontent.com/55706543/235005590-65f2cd20-8baf-45fa-ad9e-22a70d2d02f6.png) pour cette partie

On avais dit que la personne se met disponible ou pas en mode boolean, cetais pas utile ca comme feature 🤔

**Comment by CinquinAndy** [comment]
je met en v2 alors, ça pourra être bien de l'avoir pour plus tard en vrai
