### ISSUE TITLE
Manque les options dans /me-makeup

### ISSUE THREAD

**Issue by CinquinAndy** [For-Hives/api-my-makeup#58]
![image](https://user-images.githubusercontent.com/55706543/235373047-568895ad-6e87-4791-89e1-7ab3974ccefc.png)

le retour d'api fait ça : 
![image](https://user-images.githubusercontent.com/55706543/235373056-afd86b32-7038-49ab-bd65-b13b00bd22a4.png)

**Comment by CinquinAndy** [comment]
il manque la photo de profil encore

**Comment by LightInn** [comment]
> il manque la photo de profil encore

Oopsi 👀
